### ISSUE TITLE
Math error during execution.

### ISSUE THREAD

**Issue by charles-killian** [alx77/renderd_list_geo#1]
I am getting the following error when I try to execute the script.

ckillian@wb6yok-osm:~/Downloads/render_list_geo.pl-master$ sudo ./render_list_geo.pl -n 4 -z 10 -Z 18 -x 37 -X 47 -y -109 -Y -114

Rendering started at: Sat Oct 17 21:32:47 MDT 2015

Can't take log of -0.167343 at ./render_list_geo.pl line 37.
ckillian@wb6yok-osm:~/Downloads/render_list_geo.pl-master$ 

Please let me know what you think is going on.

Chuck...

**Comment by psinghsp** [comment]
I have the same problem. The formula seems to be incorrect.

**Comment by alx77** [comment]
Probably too late, but try to change the order of "y" and "Y" values, I didn't check them, the script is very simple

**Comment by bwindsor** [comment]
@charles-killian Probably too late even more - you've got x and y the wrong way round - remember x is longitude (between -180 and +180) and y is latitude (between -90 and +90).
