### ISSUE TITLE
Ability to force rerender?

### ISSUE THREAD

**Issue by SomeoneElseOSM** [alx77/renderd_list_geo#8]
Is passing the flag through to render_list something that you'd consider adding?  If so, I can create a pull request from:

https://github.com/alx77/render_list_geo.pl/compare/master...SomeoneElseOSM:force_option

Of course there may be a better way of adding a flag without an argument in perl rather than asking the user to type "-f 1" - if so I'd be happy to change that accordingly.

**Comment by alx77** [comment]
just remove colon after "f" letter  in the getopts formatted line and make pull request, I'll gladly add  it to my branch.
